### ISSUE TITLE
MSCRM Export Solution: An Unexpected Error occurred

### ISSUE THREAD

**Issue by JoostVeldhuis** [WaelHamze/xrm-ci-framework#176]
In my Solution Export VSTS task an Exception is thrown. After setting debug mode this is the stack trace with the most usefull errormessage. When I export the solution manually no errors occur.

Message: System.AggregateException: One or more errors occurred. ---> System.Security.Cryptography.CryptographicException: Keyset does not exist
2018-12-07T08:05:48.0559799Z ##[debug]
2018-12-07T08:05:48.0581628Z ##[debug]   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
2018-12-07T08:05:48.0600006Z ##[debug]   at Microsoft.Crm.ObjectModel.CanvasAppTokenService.RetrieveToken()
2018-12-07T08:05:48.0629944Z ##[debug]   at Microsoft.Crm.Tools.Core.ImportExportPublish.CanvasAppHandlerInternal.<GetCanvasAppDefinition>d__20.MoveNext()
2018-12-07T08:05:48.0648010Z ##[debug]--- End of stack trace from previous location where exception was thrown ---
2018-12-07T08:05:48.0668184Z ##[debug]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2018-12-07T08:05:48.0686062Z ##[debug]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2018-12-07T08:05:48.0706178Z ##[debug]   at Microsoft.Crm.Tools.Core.ImportExportPublish.CanvasAppHandlerInternal.<AddBlobFileXmlNodes>d__19.MoveNext()
2018-12-07T08:05:48.0724491Z ##[debug]   --- End of inner exception stack trac...).

**Comment by JoostVeldhuis** [comment]
I did some more research on the error and it only occurs when you have a Canvas app in the dynamics solution. When I remove the Canvas app I can export the solution normally. This is a new feature in the Dynamics solution structure.

**Comment by WaelHamze** [comment]
@JoostVeldhuis Thanks for the update much appreciated. I would suggest you raise a case with MS as this is likely caused by the backend. Let me know if there are any changes I can do to make this work.
