### ISSUE TITLE
MSCRM Package Deployer error: The size necessary to buffer the XML content exceeded the buffer quota.

### ISSUE THREAD

**Issue by Buddy3000** [WaelHamze/xrm-ci-framework#191]
I am attempting to deploy a solution to Dynamics 365 from an Azure DevOps pipeline using MSCRM Package Deployer. It used to work, but now always fails. Attached is an extract from the pipeline log.

[PackageDeployerLog.txt](https://github.com/WaelHamze/xrm-ci-framework/files/2822641/PackageDeployerLog.txt)

The important part of the log is:

`PackageDeployer Error: 2 : Message: WASolution - Importing solution threw and unforeseen exception`
`Source	: mscorlib`
`Method	: HandleReturnMessage`
`Error	: The size necessary to buffer the XML content exceeded the buffer quota.`

Stack trace and other information can be viewed in the attachment.

**Comment by WaelHamze** [comment]
@Buddy3000 looks like this error is coming from Package Deployer it self. I suggest you try running this on your workstation and see if you get similar behaviour. You could also raise a case with MS for this. Finally as an alternative you could use the Solution Import task provided with the toolkit.

**Comment by charliechen179** [comment]
@WaelHamze @Buddy3000 I'm having the same issue right now. I tried to run the package deployer on my local machine, but I get the same error message. Do you have any clue? Thanks.

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Verbose	16	7/29/2019 12:21:01  Failed to Execute Command - ImportSolution : RequestID=3d44c33c-05b5-4cbe-be3e-d77f7d3d39ca : duration=00:00:16.9776490
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	7/29/2019 12:21:01  ************ Exception - ImportSolution : Executing ImportSolutionRequest for ImportSolutionToCrm |=> The size necessary to buffer the XML content exceeded the buffer quota.
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 7/29/2019
Time	: 12:21:01
Error	: The size necessary to buffer the XML content exceeded the buffer quota.
Stack Trace	: Server stack trace: 
   at System.Runtime.BufferedOutputStream.WriteCore(Byte[] buffer, Int32 offset, Int32 size)
   at System.Runtime.BufferedOutputStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Xml.XmlBinaryNodeWriter.FlushBuffer()
   at System.Xml.XmlStreamNodeWriter.UnsafeWriteUTF8Chars(Char* chars, Int32 charCount)
   at System.Xml.XmlBinaryNodeWriter.UnsafeWriteText(Char* chars, Int32 charCount)
   at System.Xml.XmlBinaryNodeWriter.WriteText(Char[] chars, Int32 offset, Int32 count)
   at System.Xml.XmlBinaryNodeWriter.WriteEscapedText(Char[] chars, Int32 offset, Int32 count)
   at System.Xml.XmlBaseWriter.WriteChars(Char[] chars, Int32 offset, Int32 count)
   at System.Xml.XmlBinaryWriter.WriteTextNode(XmlDictionaryReader reader, Boolean attribute)
   at System.Xml.XmlDictionaryWriter.WriteNode(XmlDictionaryReader reader, Boolean defattr)
   at System.ServiceModel.Channels.ReceivedFault.CreateFault11(XmlDictionaryReader reader, Int32 maxBufferSize)
   at System.ServiceModel.Channels.MessageFault.CreateFault(Message message, Int32 maxBufferSize)
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at Microsoft.Xrm.Sdk.IOrganizationService.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.<>c__DisplayClass40_0.<ExecuteCore>b__0()
   at Microsoft.Xrm.Sdk.WebServiceClient.WebProxyClient`1.ExecuteAction[TResult](Func`1 action)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.ExecuteCore(OrganizationRequest request)
   at Microsoft.Xrm.Sdk.WebServiceClient.OrganizationWebProxyClient.Execute(OrganizationRequest request)
   at Microsoft.Xrm.Tooling.Connector.CrmServiceClient.CrmCommand_Execute(OrganizationRequest req, String `errorStringCheck)```

**Comment by charliechen179** [comment]
@WaelHamze @Buddy3000 I think my issue is mainly because I deployed a new managed solution having dependencies in unmanaged solution.

**Comment by Buddy3000** [comment]
@charliechen179 

This was 6 months ago so forgive my mind being a bit hazy. I solved a few problems back then, and I cannot remember which solution solved which problem, but I think the solution below is the correct one for this problem. If not then please reply and I'll rack my brain some more.

If you crack open the solution zip file you will find a data.xml file within. Opening this file, you should see a line like this at the top:

`<entities xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" timestamp="15/01/2019 12:32:18">`

The problem arises because of the timestamp value, and I think it is a locale issue. When I extracted the zip, I extracted using my local machine with a UK locale. But on upload, I used an Azure DevOps agent that was running on a US locale. And so it threw a wobbly because 15/01/2019 is not a valid US date (for the US the equivalent date would be written 01/15/2019).

Fortunately, the file will upload just as happily if you strip out this timestamp. I.e. replace the line above with this and all is good and should work:

`<entities xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">`

So I fixed this with a little PowerShell, that unzipped the file, removed the timestamp attribute, and then zipped it all back up again.

The key lines of PowerShell that I wrote for this are:

`Expand-Archive -LiteralPath $zipfile -DestinationPath $tempDirectory -Force`
`[xml]$data = Get-Content -Path $dataFile`
`$data.entities.Attributes.RemoveNamedItem("timestamp")`
`$data.Save($dataFile)`
`Compress-Archive -Path $tempDirectory\* -DestinationPath $zipfile -Force`

Hope that helps? Let me know how you get on.

**Comment by charliechen179** [comment]
@Buddy3000 Thank you very much for sharing your great experience.
My issue is a little bit different as I try to deploy a managed solution depending on the unmanaged components.
