### ISSUE TITLE
Unable to pack solution

### ISSUE THREAD

**Issue by daveburman** [WaelHamze/xrm-ci-framework#195]
Hi @WaelHamze 

Our DevOps instance started using 10.0.4 today, and now we're having an issue using the MSCRM Pack Solution task.  The following exception is thrown immediately after the mapping directives are read:
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

SolutionPackager: Exception thrown: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.AggregateCatalog.GetExports(ImportDefinition definition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InternalGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.InnerCatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExports(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CatalogExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.AggregateExportProvider.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.GetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ExportProvider.TryGetExportsCore(ImportDefinition definition, AtomicComposition atomicComposition, IEnumerable`1& exports)
   at System.ComponentModel.Composition.Hosting.ExportProvider.GetExports(ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TryGetExports(ExportProvider provider, ComposablePart part, ImportDefinition definition, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportSubset(PartManager partManager, IEnumerable`1 imports, AtomicComposition atomicComposition)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImportsStateMachine(PartManager partManager, ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ImportEngine.TrySatisfyImports(PartManager partManager, ComposablePart part, Boolean shouldTrackImports)
   at System.ComponentModel.Composition.Hosting.ImportEngine.SatisfyImports(ComposablePart part)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.<>c__DisplayClass19_0.<Compose>b__0()
   at System.ComponentModel.Composition.Hosting.CompositionServices.TryInvoke(Action action)
   at System.ComponentModel.Composition.Hosting.ComposablePartExportProvider.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.Hosting.CompositionContainer.Compose(CompositionBatch batch)
   at System.ComponentModel.Composition.AttributedModelServices.ComposeParts(CompositionContainer container, Object[] attributedParts)
   at Microsoft.Crm.Tools.SolutionPackager.Context..ctor(PackagerArguments arguments)
   at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager..ctor(PackagerArguments arguments)
   at Microsoft.Crm.Tools.SolutionPackager.Program.Main(String[] args), returning error code '1'
CrmSvcUtil Runtime = 00:00:02.3992627
System.Management.Automation.InformationRecord
##[error]Packing Solution failed. Check logs for more information
##[section]Finishing: MSCRM Pack Solution

There's been no significant changes in our codebase overnight, and builds have been successful on a daily basis for a while now (using 10.0.3).  We did have a couple of plug-ins on a lower version of .NET so I've upgraded those, but it's made no difference.

We're using a custom build server (Windows Server 2016).  .NET 4.6.2 is present.

I've rolled back to the v9 task as a workaround which has allowed the build to complete successfully, although I've yet to attempt a release.

Any ideas?

**Comment by WaelHamze** [comment]
@daveburman this seems similar to this issue. https://github.com/WaelHamze/dyn365-ce-vsts-tasks/issues/49

Can you give it a try now please.

**Comment by daveburman** [comment]
Thanks @WaelHamze, didn't see that.  I've just run another build and am getting the same issue, but the version of the MSCRM Tool Installer is still 9.0.76, so I guess the hotfix has not yet synced to us.  I'll keep monitoring it for a couple of days and come back to you.

Thanks

Dave

**Comment by daveburman** [comment]
Hi @WaelHamze 

Unfortunately the error persists with task version 10.0.4, same details as above.

The issue appears to be related to a new dll in the coretools folder; System.ValueTuple.dll.  I managed to reproduce the problem locally on the build agent, and after I copied this dll into the folder, the pack completes successfully.  Hope that helps!

**Comment by WaelHamze** [comment]
@daveburman thanks for the investigation this helps a lot. You are right I use ILSpy and solutionpackager.exe has a dependency on this DLL.

Now I packed several solutions on hosted and private agents include WS 2012 R2 and never had any issues. I suspect either the runtime on these machines has this DLL loaded or for some reason your solution is exercising a certain path in the code that requires this DLL and I am not.

Either way I have added it to the lib and release a new version to the marketplace 9.6.6

Once this syncs into your account you should see the below version of the task. Let me know if this works for you.

==============================================================================
Task         : MSCRM Tool Installer
Description  : Installs the Dynamics 365 tools required by all of the tasks
Version      : 9.0.85
Author       : Wael Hamze
Help         : Tools are installed under {agentroot}/_work/tools. e.g 'D:\Agent1_work\tools\MSCRMBuildTools\9.0.1'
==============================================================================

**Comment by WaelHamze** [comment]
Closing if you still have error please re-open
