### ISSUE TITLE
MSCRM Plugin Registration: Object reference not set to instance of an object.

### ISSUE THREAD

**Issue by devmzeshan** [WaelHamze/xrm-ci-framework#214]
Hi Wael,

We are having this issue when using MSCRM Plugin Registration task and this issue is happening while trying to register "Create" step for plugin assembly.

![2019-05-21_14-36-41](https://user-images.githubusercontent.com/43203374/58085390-1100e580-7bd6-11e9-9169-4e2fe4b076ab.jpg)
![2019-05-21_14-37-00](https://user-images.githubusercontent.com/43203374/58085394-15c59980-7bd6-11e9-8e61-d15eba4c387f.jpg)

**Comment by devmzeshan** [comment]
@WaelHamze Can you please update on this?

thanks..

**Comment by WaelHamze** [comment]
@devmzeshan please set system.debug = true and share the logs

**Comment by devmzeshan** [comment]
@WaelHamze Apologies for the delayed response, I have attached the logs. 
[ReleaseLogs_63.zip](https://github.com/WaelHamze/xrm-ci-framework/files/3319538/ReleaseLogs_63.zip)

**Comment by devmzeshan** [comment]
@WaelHamze any updates on this?

**Comment by strwase** [comment]
I seem to experience a similar issue.
the registration seems to work tough.
plugin assembly, plugin and the step get registered, but it still throws an exception.

`##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Set-XrmPluginRegistration : Object reference not set to an instance of an object.
##[debug]At C:\Agent\_work\tools\MSCRMBuildTools\9.1.2\xRMCIFramework\9.0.0\PluginRegistration.ps1:40 char:1
##[debug]+ Set-XrmPluginRegistration -RegistrationType $RegistrationType -Assemb ...
##[debug]+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
##[debug]    + CategoryInfo          : NotSpecified: (:) [Set-XrmPluginRegistration], NullReferenceException
##[debug]    + FullyQualifiedErrorId : System.NullReferenceException,Xrm.Framework.CI.PowerShell.Cmdlets.SetXrmPluginRegistrati    on
##[debug] 
##[debug]Script stack trace:
##[debug]at <ScriptBlock>, C:\Agent\_work\tools\MSCRMBuildTools\9.1.2\xRMCIFramework\9.0.0\PluginRegistration.ps1: line 40
##[debug]at <ScriptBlock>, C:\Agent\_work\_tasks\MSCRMPluginRegistration_a48708ef-a5d6-4af5-a9be-589847132834\11.0.1\MSCRMPluginRegistration.ps1: line 38
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]at <ScriptBlock>, <No file>: line 22
##[debug]at <ScriptBlock>, <No file>: line 18
##[debug]at <ScriptBlock>, <No file>: line 1
##[debug]Exception:
##[debug]System.NullReferenceException: Object reference not set to an instance of an object.
##[debug]   at Xrm.Framework.CI.Common.PluginRegistrationHelper.UpsertPluginTypeAndSteps(Guid parentId, Type pluginType, String solutionName, RegistrationTypeEnum registrationType)
##[debug]   at Xrm.Framework.CI.PowerShell.Cmdlets.SetXrmPluginRegistration.ProcessRecord()
##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
`

**Comment by qdi-jeffd** [comment]
I am actually just having troubles figuring out how to generate the plugin mapping file. There doesn't seem to be any documentation around this, although I did find the schema and a sample json so I guess I'll manually build it.

PS @devmzeshan Just wanted to highlight that your password is in your logs, if you haven't already changed it.

**Comment by strwase** [comment]
@qdi-jeffd, you can only generate a schema based on an existing registration. You can do that with the power shell cmdlets. But for new registrations, you'll have to create the mapping manually

**Comment by WaelHamze** [comment]
@qdi-jeffd If you have plug-ins in your environment already. You can use this script to generate the mapping file.

https://github.com/WaelHamze/dyn365-ce-devops-sample/blob/master/Sample/Xrm.CI.Framework.Sample/Xrm.CI.Framework.Sample.Plugins/GetPluginRegistration.ps1

I see many users generate the steps etc.. using plug-in registration tool in env and then generate a json from that.

You can also do this manually if you like and if you are familiar with the object model. You can link your mapping file to this schema file in visual studio which will give you some intellisense

https://github.com/WaelHamze/xrm-ci-framework/blob/master/MSDYNV9/Xrm.Framework.CI/Xrm.Framework.CI.Common/PluginRegistration/PluginRegistrationSchema.json

**Comment by WaelHamze** [comment]
@strwase can you share the mapping file?

I am specifically interested in what is in the mapping file after this step and how is this different than previous steps.

2019-06-24T06:34:28.6261028Z ##[debug]Upsert SdkMessageProcessingStep 7c18d1a2-1b3a-4e89-990b-d2d1d8ed43bf completed

**Comment by strwase** [comment]
Hi @WaelHamze, 

here is the mappingfile i'm using.

`{
	"$schema": "./PluginRegistrationSchema.json",
	"Id": "{9e9d9681-b7b5-46a4-8c45-77a4f56a6a95}",
	"Name": "Norriq.Crm.Codipack.Plugins.dll",
	"IsolationMode": "Sandbox",
	"SourceType": "Database",
	"PluginTypes": [
		{
			"Id": "{8876e445-d064-4b0f-84ec-4d9932cb5983}",
			"Name": "Norriq.Crm.Codipack.Plugins.QuotePropertyTemplate.CopyTemplateQuestions: Create of nrq_quotepropertiestemplate",
			"FriendlyName": "0d6cf174-4b19-437a-ac51-9ba0c4c37cab",
			"TypeName": "Norriq.Crm.Codipack.Plugins.QuotePropertyTemplate.CopyTemplateQuestions",
			"Steps": [
				{
					"Id": "{c4a291af-33b9-4802-8ffa-5ed99187c9b5}",
					"Name": "Norriq.Crm.Codipack.Plugins.QuotePropertyTemplate.CopyTemplateQuestions: Create of nrq_quotepropertiestemplate",
					"MessageName": "Create",
					"PrimaryEntityName": "nrq_quotepropertiestemplate",
					"Mode": "Synchronous",
					"Stage": "Postoperation",
					"SupportedDeployment": "ServerOnly",
					"StateCode": "Enabled",
					"Rank": 1,
					"AsyncAutoDelete": false
				}
			]
		}
	]
}
`

as far as I can tell, the step registration completes, but then an exception get thrown from somewhere.

`##[debug]Upsert SdkMessageProcessingStep c4a291af-33b9-4802-8ffa-5ed99187c9b5 completed
##[debug]Caught exception from task script.
##[debug]Error record:
##[debug]Set-XrmPluginRegistration : Object reference not set to an instance of an object.
##[debug]At C:\Agent\_work\tools\MSCRMBuildTools\9.1.2\xRMCIFramework\9.0.0\PluginRegistration.ps1:40 char:1
##[debug]+ Set-XrmPluginRegistration -RegistrationType $RegistrationType -Assemb ...
`

**Comment by qdi-jeffd** [comment]
@WaelHamze I do have an existing plugin that I am trying to automate deployment of. I cannot get that script to work for my environment it seems though. I am connecting to an organization on D365 and if I use the url of the organization I get the following:

The service '/XRMServices/2011/Discovery.svc' cannot be activated due to an exception during compilation.  The exception message is: Could not load file or assembly
'Microsoft.Crm.Site.Services.

Which a little research shows for that for D365 I need to use the discovery url, but providing that isn't working either. The error I get when I switch to the disco url is:
Unable to login to Dynamics CRM, Error was : clientCredentials.UserName.UserName or clientCredentials.Windows.ClientCredential.UserName MUST be populated!

I have been providing the credentials though. I started building the mapping file manually, but it would be great to figure out what I am doing wrong to generate it via the script.

Thanks!

**Comment by qdi-jeffd** [comment]
I still am having no luck with getting the script to generate my mapping file. I was able to get a connection string formatted that works through XrmToolBox (turns out some of the issues I was having were due to federated security on my account and MFA). Using an App registration and client secret I can get xrmtoolkit connecting, but not the powershell script. I am getting the error I mentioned above about Microsoft.Crm.Site.Services even when I use the disco url.

With a manually created partial mapping file (just did the first plugin and step). I get to the same point as the other two users here and get the Object reference error.

Any help you can give is appreciated. If it helps to know more about our environments to see what is common I am running the plugin registration through a pipeline in Azure DevOps On prem. The build agents run on Windows Server, I could grab some other versions if needed but Power Shell is on version 5.1.14409.1018.

**Comment by qdi-jeffd** [comment]
@strwase @devmzeshan FYI In my case it turned out to be bad json for the plugins. Specifically that I had put 
"Images": null
Instead of 
"Images": []

As the specific plugin that I was testing with did not have images for any of it's steps.

I still cannot generate the json file though.

Jeff

**Comment by tklooster** [comment]
Try copying your plugin dll to your script folder where you are running.  I was getting a blank json file generated before I did this.  Works great now.
