### ISSUE TITLE
Can't verify as import job couldn't be found. Error Message: Unhandled Exception: System.Web.HttpException: Invalid use of SimpleWorkerRequest constructor. Application path cannot be overridden in this context. Please use SimpleWorkerRequest constructor that does not override the application path.

### ISSUE THREAD

**Issue by nikitaus** [WaelHamze/xrm-ci-framework#240]
Hi all,

I am facing an issue with "Import Solution". Is there any thoughts how to fix that?

```
2019-10-24T19:13:47.1552209Z ##[section]Starting: TARGET: Import Solution XXXXXXX
2019-10-24T19:13:47.1552209Z ==============================================================================
2019-10-24T19:13:47.1552337Z Task         : MSCRM Import Solution
2019-10-24T19:13:47.1552832Z Description  : Import a Dynamics CRM Solution package
2019-10-24T19:13:47.1552922Z Version      : 11.0.4
2019-10-24T19:13:47.1552998Z Author       : Wael Hamze
2019-10-24T19:13:47.1553105Z Help         : This task invokes ImportSolutionRequest in Async mode
2019-10-24T19:13:47.1553204Z ==============================================================================
2019-10-24T19:13:48.7083430Z Importing Solution: C:\Iteco_agent\_work\r2\a\XXXXXXX.zip
2019-10-24T19:13:48.7093459Z Solution Zip Size: 1.44 MB
2019-10-24T19:13:48.7295460Z Solution Unique Name: XXXXXXX, Version: 2019.10.24.1
2019-10-24T19:13:48.7768197Z XXXXXXX currently installed with version: 2019.10.24.3
2019-10-24T19:14:04.5764142Z Async Operation completed with status: Failed
2019-10-24T19:14:04.5766020Z Async Operation completed with message: Unhandled Exception: System.Web.HttpException: Invalid use of SimpleWorkerRequest constructor. Application path cannot be overridden in this context. Please use SimpleWorkerRequest constructor that does not override the application path.
2019-10-24T19:14:04.5766761Z    at System.Web.Hosting.SimpleWorkerRequest..ctor(String appVirtualDir, String appPhysicalDir, String page, String query, TextWriter output)
2019-10-24T19:14:04.5767127Z    at Microsoft.Crm.Extensibility.InternalSdkContextInitializer.SetHttpContext(WindowsIdentity windowsIdentity, Guid organizationId, Guid callerId)
2019-10-24T19:14:04.5767333Z    at Microsoft.Crm.Extensibility.InprocessServiceProxy.ExecuteCore(OrganizationRequest request)
2019-10-24T19:14:04.5767605Z    at Microsoft.Crm.Asynchronous.ExecuteSdkMessageOperation.InternalExecute(AsyncEvent asyncEvent)
2019-10-24T19:14:04.5768187Z 
2019-10-24T19:14:04.8732176Z ##[error]Can't verify as import job couldn't be found. Error Message: Unhandled Exception: System.Web.HttpException: Invalid use of SimpleWorkerRequest constructor. Application path cannot be overridden in this context. Please use SimpleWorkerRequest constructor that does not override the application path.
   at System.Web.Hosting.SimpleWorkerRequest..ctor(String appVirtualDir, String appPhysicalDir, String page, String query, TextWriter output)
   at Microsoft.Crm.Extensibility.InternalSdkContextInitializer.SetHttpContext(WindowsIdentity windowsIdentity, Guid organizationId, Guid callerId)
   at Microsoft.Crm.Extensibility.InprocessServiceProxy.ExecuteCore(OrganizationRequest request)
   at Microsoft.Crm.Asynchronous.ExecuteSdkMessageOperation.InternalExecute(AsyncEvent asyncEvent)

2019-10-24T19:14:04.9091038Z ##[section]Finishing: TARGET: Import Solution XXXXXXX

```

**Comment by herr-mueller** [comment]
Hi @nikitaus, I've got the same problem currently while running the build tasks on Azure DevOps.
I saw you closed the issue, can you tell me, how you solved this?

**Comment by befaes** [comment]
Hi @nikitaus , @herr-mueller . I've got the same problem. Was a solution found for this issue?

**Comment by befaes** [comment]
Removed all from Azure DevOps and reimported as new items. Next no longer experienced the build issue.

**Comment by pork1977** [comment]
Hi @nikitaus how did you solve this? same problem has just starting happening for us and despite my best efforts in trying to fix, I have yet to be successful!

**Comment by Emzil** [comment]
For those who looking for the same. IISRESET helps.
