### ISSUE TITLE
Import solution TFS task : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by Bakanych** [WaelHamze/xrm-ci-framework#58]
Task version: 8.0.3

Some task runs I get 
`##[error]Object reference not set to an instance of an object`
in TFS task log.

Is it possible to get more details to understand the error cause?

**Comment by WaelHamze** [comment]
I would suggest you get the Ping task working first. Normally I see this error happening when the connection string is not valid and unfortunately it comes directly from the SDK with no additional details. Please share your connection string and details on where you are trying to connect to.

**Comment by WaelHamze** [comment]
You can try to log the build/release with system.debug set to true (definition variable) this will output more details into the log.

**Comment by Bakanych** [comment]
> Normally I see this error happening when the connection string is not valid
I do ping as a first task and then we have task group to import set of solutions.
The problem is that error occurs randomly for different solutions during same release deployment.

**Comment by Bakanych** [comment]
I tried system.debug. Error cause is:

```
2017-10-26T23:59:58.9926721Z ##[debug]Caught exception from task script.
2017-10-26T23:59:58.9926721Z ##[debug]Error record:
2017-10-26T23:59:59.1801565Z ##[debug]Get-XrmSolution : Object reference not set to an instance of an object.
2017-10-26T23:59:59.1801565Z ##[debug]At C:\agent5\_work\_tasks\MSCRMImportSolution_4455576d-d40a-4234-ad75-3d7ff40ec76e\8.1.3\ps_modules\xRMCIFramework\ImportSolution.ps1:51 char:13
2017-10-26T23:59:59.1801565Z ##[debug]+ $solution = Get-XrmSolution -ConnectionString "$CrmConnectionString"  ...
2017-10-26T23:59:59.1801565Z ##[debug]+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-10-26T23:59:59.1957835Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Get-XrmSolution], NullReferenceException
2017-10-26T23:59:59.1957835Z ##[debug]    + FullyQualifiedErrorId : System.NullReferenceException,Xrm.Framework.CI.PowerShell.Cmdlets.GetXrmSolutionCommand
2017-10-26T23:59:59.1957835Z ##[debug] 
2017-10-26T23:59:59.1957835Z ##[debug]Script stack trace:
2017-10-26T23:59:59.2114081Z ##[debug]at <ScriptBlock>, C:\agent5\_work\_tasks\MSCRMImportSolution_4455576d-d40a-4234-ad75-3d7ff40ec76e\8.1.3\ps_modules\xRMCIFramework\ImportSolution.ps1: line 51
2017-10-26T23:59:59.2114081Z ##[debug]at <ScriptBlock>, C:\agent5\_work\_tasks\MSCRMImportSolution_4455576d-d40a-4234-ad75-3d7ff40ec76e\8.1.3\MSCRMImportSolution.ps1: line 43
2017-10-26T23:59:59.2114081Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-10-26T23:59:59.2114081Z ##[debug]at <ScriptBlock>, <No file>: line 22
2017-10-26T23:59:59.2270339Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-10-26T23:59:59.2270339Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-10-26T23:59:59.2270339Z ##[debug]Exception:
2017-10-26T23:59:59.2426588Z ##[debug]System.NullReferenceException: Object reference not set to an instance of an object.
2017-10-26T23:59:59.2426588Z ##[debug]   at Xrm.Framework.CI.PowerShell.Cmdlets.XrmCommandBase.BeginProcessing()
2017-10-26T23:59:59.2426588Z ##[debug]   at System.Management.Automation.Cmdlet.DoBeginProcessing()
2017-10-26T23:59:59.2426588Z ##[debug]   at System.Management.Automation.CommandProcessorBase.DoBegin()
2017-10-26T23:59:59.3207827Z ##[error]Object reference not set to an instance of an object.
2017-10-26T23:59:59.3207827Z ##[debug]Processed: ##vso[task.logissue type=error]Object reference not set to an instance of an object.
2017-10-26T23:59:59.3207827Z ##[debug]Processed: ##vso[task.complete result=Failed]
```

**Comment by WaelHamze** [comment]
Pull Request merged. Will let you know once it is live.

**Comment by WaelHamze** [comment]
This change is live now. 8.3.1
