### ISSUE TITLE
Get-CrmInstances returns internal server error

### ISSUE THREAD

**Issue by Bakanych** [WaelHamze/xrm-ci-framework#63]
At least 2 TFS tasks: "Set Admin mode" and "Backup instance" currently return "internal server error":
```
2017-11-05T01:46:49.1449332Z ##[debug]Caught exception from task script.
2017-11-05T01:46:49.1449332Z ##[debug]Error record:
2017-11-05T01:46:49.3324287Z ##[debug]Get-CrmInstances : Operation returned an invalid status code 'InternalServerError'
2017-11-05T01:46:49.3324287Z ##[debug]At C:\agent5\_work\_tasks\MSCRMSetOnlineInstanceAdminMode_77fb5553-32fe-471d-8e77-ae540bf7a32c\8.0.5\OnlineInstanceFunctions.ps1:14 char:15
2017-11-05T01:46:49.3324287Z ##[debug]+     $instances = Get-CrmInstances -ApiUrl $ApiUrl -Credential $Cred
2017-11-05T01:46:49.3480680Z ##[debug]+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2017-11-05T01:46:49.3480680Z ##[debug]    + CategoryInfo          : NotSpecified: (:) [Get-CrmInstances], HttpOperationException
2017-11-05T01:46:49.3480680Z ##[debug]    + FullyQualifiedErrorId : Microsoft.Rest.HttpOperationException,Microsoft.Xrm.OnlineManagementAPI.GetCrmInstances
2017-11-05T01:46:49.3480680Z ##[debug] 
2017-11-05T01:46:49.3480680Z ##[debug]Script stack trace:
2017-11-05T01:46:49.3636832Z ##[debug]at Get-XrmInstanceByName, C:\agent5\_work\_tasks\MSCRMSetOnlineInstanceAdminMode_77fb5553-32fe-471d-8e77-ae540bf7a32c\8.0.5\OnlineInstanceFunctions.ps1: line 14
2017-11-05T01:46:49.3636832Z ##[debug]at <ScriptBlock>, C:\agent5\_work\_tasks\MSCRMSetOnlineInstanceAdminMode_77fb5553-32fe-471d-8e77-ae540bf7a32c\8.0.5\SetOnlineInstanceAdminMode.ps1: line 55
2017-11-05T01:46:49.3636832Z ##[debug]at <ScriptBlock>, C:\agent5\_work\_tasks\MSCRMSetOnlineInstanceAdminMode_77fb5553-32fe-471d-8e77-ae540bf7a32c\8.0.5\MSCRMSetOnlineInstanceAdminMode.ps1: line 32
2017-11-05T01:46:49.3793181Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-11-05T01:46:49.3793181Z ##[debug]at <ScriptBlock>, <No file>: line 22
2017-11-05T01:46:49.3793181Z ##[debug]at <ScriptBlock>, <No file>: line 18
2017-11-05T01:46:49.3793181Z ##[debug]at <ScriptBlock>, <No file>: line 1
2017-11-05T01:46:49.3793181Z ##[debug]Exception:
2017-11-05T01:46:49.3949333Z ##[debug]Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'InternalServerError'
2017-11-05T01:46:49.3949333Z ##[debug]   at Microsoft.Xrm.OnlineManagementAPI.GetCrmInstances.ProcessRecord()
2017-11-05T01:46:49.3949333Z ##[debug]   at System.Management.Automation.CommandProcessor.ProcessRecord()
2017-11-05T01:46:49.4730565Z ##[error]Operation returned an invalid status code 'InternalServerError'
```

**Comment by WaelHamze** [comment]
I tried the Cmdlet directly outside of the task. This is currently failing too. You could try that at your end too. This seems like a temporary issue at the vendor site. You could raise a case if you get the same error executing the Cmdlet directly.

**Comment by WaelHamze** [comment]
The API seems to be working again now. Hopefully it works for you too.
